
import { RUPData } from './types';

export const INITIAL_DATA: RUPData[] = [
  {
    "asal_dana": "APBD",
    "asal_dana_klpd": "Kab. Muko Muko",
    "asal_dana_satker": "Sekretariat Daerah",
    "jenis_klpd": "KABUPATEN",
    "kd_rup": 62843031,
    "kd_satker": 94683,
    "kd_satker_str": "4.01.2.16.2.19.01.0000",
    "mak": "4.01.03.2.01.0001...",
    "nama_paket": "Belanja Makanan dan Minuman Rapat",
    "nama_klpd": "Kab. Muko Muko",
    "nama_satker": "Sekretariat Daerah",
    "pagu": 2055000,
    "status_aktif_rup": true,
    "status_delete_rup": false,
    "status_umumkan_rup": "Terumumkan",
    "sumber_dana": "APBD",
    "tahun_anggaran": 2026,
    "tahun_anggaran_dana": 2026,
    "bulan_pengadaan": "Januari",
    "jenis_paket": "Penyedia",
    "metode_pengadaan": "E-Purchasing",
    "volume_pekerjaan": "1 Paket",
    "spesifikasi_pekerjaan": "Kudapan; Nasi Kotak;",
    "jenis_pengadaan": "Barang"
  },
  {
    "asal_dana": "APBD",
    "asal_dana_klpd": "Kab. Muko Muko",
    "asal_dana_satker": "Sekretariat Daerah",
    "jenis_klpd": "KABUPATEN",
    "kd_rup": 62843225,
    "kd_satker": 94683,
    "kd_satker_str": "4.01.2.16.2.19.01.0000",
    "mak": "4.01.03.2.01.0002...",
    "nama_paket": "Belanja Alat/Bahan untuk Kegiatan Kantor- Bahan Cetak",
    "nama_klpd": "Kab. Muko Muko",
    "nama_satker": "Sekretariat Daerah",
    "pagu": 2230320,
    "status_aktif_rup": true,
    "status_delete_rup": false,
    "status_umumkan_rup": "Terumumkan",
    "sumber_dana": "APBD",
    "tahun_anggaran": 2026,
    "tahun_anggaran_dana": 2026,
    "bulan_pengadaan": "Januari",
    "jenis_paket": "Penyedia",
    "metode_pengadaan": "E-Purchasing",
    "volume_pekerjaan": "1 Paket",
    "spesifikasi_pekerjaan": "Spanduk; Foto Kopi; Penjilidan;",
    "jenis_pengadaan": "Barang"
  },
  {
    "asal_dana": "APBD",
    "asal_dana_klpd": "Kab. Muko Muko",
    "asal_dana_satker": "Dinas Kesehatan",
    "jenis_klpd": "KABUPATEN",
    "kd_rup": 77123456,
    "kd_satker": 12345,
    "kd_satker_str": "1.02.0.00.0.00.01.0000",
    "mak": "1.02.01.2.02.0005...",
    "nama_paket": "Penyelenggaraan Fogging Fokus DBD",
    "nama_klpd": "Kab. Muko Muko",
    "nama_satker": "Dinas Kesehatan",
    "pagu": 45000000,
    "status_aktif_rup": true,
    "status_delete_rup": false,
    "status_umumkan_rup": "Terumumkan",
    "sumber_dana": "APBD",
    "tahun_anggaran": 2026,
    "tahun_anggaran_dana": 2026,
    "bulan_pengadaan": "Februari",
    "jenis_paket": "Swakelola",
    "metode_pengadaan": "Swakelola Tipe I",
    "volume_pekerjaan": "12 Kali",
    "spesifikasi_pekerjaan": "Operasional Fogging;",
    "jenis_pengadaan": "Jasa Lainnya"
  },
  {
    "asal_dana": "APBD",
    "asal_dana_klpd": "Kab. Muko Muko",
    "asal_dana_satker": "Dinas Pendidikan",
    "jenis_klpd": "KABUPATEN",
    "kd_rup": 77123457,
    "kd_satker": 54321,
    "kd_satker_str": "1.01.0.00.0.00.01.0000",
    "mak": "1.01.02.2.01.0008...",
    "nama_paket": "Pelatihan Kompetensi Guru SD",
    "nama_klpd": "Kab. Muko Muko",
    "nama_satker": "Dinas Pendidikan",
    "pagu": 125000000,
    "status_aktif_rup": true,
    "status_delete_rup": false,
    "status_umumkan_rup": "Terumumkan",
    "sumber_dana": "APBD",
    "tahun_anggaran": 2026,
    "tahun_anggaran_dana": 2026,
    "bulan_pengadaan": "Maret",
    "jenis_paket": "Swakelola",
    "metode_pengadaan": "Swakelola Tipe II",
    "volume_pekerjaan": "1 Paket",
    "spesifikasi_pekerjaan": "Pelatihan Teknis;",
    "jenis_pengadaan": "Jasa Lainnya"
  },
  {
    "asal_dana": "APBD",
    "asal_dana_klpd": "Kab. Muko Muko",
    "asal_dana_satker": "Sekretariat Daerah",
    "jenis_klpd": "KABUPATEN",
    "kd_rup": 63102902,
    "kd_satker": 94683,
    "kd_satker_str": "4.01.2.16.2.19.01.0000",
    "mak": "4.01.01.2.08.0004...",
    "nama_paket": "Belanja Jasa Pelayanan Umum Kantor (Bagian Umum)",
    "nama_klpd": "Kab. Muko Muko",
    "nama_satker": "Sekretariat Daerah",
    "pagu": 1145441844,
    "status_aktif_rup": true,
    "status_delete_rup": false,
    "status_umumkan_rup": "Terumumkan",
    "sumber_dana": "APBD",
    "tahun_anggaran": 2026,
    "tahun_anggaran_dana": 2026,
    "bulan_pengadaan": "Januari",
    "jenis_paket": "Penyedia",
    "metode_pengadaan": "E-Purchasing",
    "volume_pekerjaan": "4 Paket",
    "spesifikasi_pekerjaan": "Tenaga Supir (Outsourcing);",
    "jenis_pengadaan": "Jasa Lainnya"
  }
];
