
import { RUPData } from './types';

export const INITIAL_DATA: RUPData[] = [
  {
    "asal_dana": "APBD",
    "asal_dana_klpd": "Kab. Muko Muko",
    "asal_dana_satker": "Dinas Tenaga Kerja dan Transmigrasi",
    "jenis_klpd": "KABUPATEN",
    "kd_rup": 63160550,
    "kd_satker": 337180,
    "kd_satker_str": "2.07.3.32.0.00.01.0000",
    "mak": "2.07.05.2.01.0003.5.1.02.01.001.00027.1.1.12.01.03.0004.00001",
    "nama_paket": "Pengadaan Bahan Logistik Kantor",
    "nama_klpd": "Kab. Muko Muko",
    "nama_satker": "Dinas Tenaga Kerja dan Transmigrasi",
    "pagu": 520000,
    "status_aktif_rup": true,
    "status_delete_rup": false,
    "status_umumkan_rup": "Terumumkan",
    "sumber_dana": "APBD",
    "tahun_anggaran": 2026,
    "tahun_anggaran_dana": 2026,
    "bulan_pengadaan": "Maret",
    "jenis_paket": "Penyedia",
    "metode_pengadaan": "Pengadaan Langsung",
    "volume_pekerjaan": "1 Paket",
    "spesifikasi_pekerjaan": "Alat Tulis Kantor",
    "jenis_pengadaan": "Barang"
  },
  {
    "asal_dana": "APBD",
    "asal_dana_klpd": "Kab. Muko Muko",
    "asal_dana_satker": "Sekretariat DPRD",
    "jenis_klpd": "KABUPATEN",
    "kd_rup": 63421750,
    "kd_satker": 87209,
    "kd_satker_str": "4.02.0.00.0.00.01.0000",
    "mak": "4.02.01.2.15.0002.5.1.02.01.001.00029.1.1.12.01.03.0006.00453",
    "nama_paket": "Belanja Cetak dan Penggandaan",
    "nama_klpd": "Kab. Muko Muko",
    "nama_satker": "Sekretariat DPRD",
    "pagu": 985400,
    "status_aktif_rup": true,
    "status_delete_rup": false,
    "status_umumkan_rup": "Terumumkan",
    "sumber_dana": "APBD",
    "tahun_anggaran": 2026,
    "tahun_anggaran_dana": 2026,
    "bulan_pengadaan": "Maret",
    "jenis_paket": "Penyedia",
    "metode_pengadaan": "Pengadaan Langsung",
    "volume_pekerjaan": "1 Paket",
    "spesifikasi_pekerjaan": "Cetak Laporan Kegiatan",
    "jenis_pengadaan": "Jasa"
  },
  {
    "asal_dana": "APBD",
    "asal_dana_klpd": "Kab. Muko Muko",
    "asal_dana_satker": "Sekretariat DPRD",
    "jenis_klpd": "KABUPATEN",
    "kd_rup": 63425027,
    "kd_satker": 87209,
    "kd_satker_str": "4.02.0.00.0.00.01.0000",
    "mak": "4.02.02.2.04.0008.5.1.02.02.004.00117.8.1.02.02.04.0117.00004",
    "nama_paket": "Belanja Sewa Peralatan dan Mesin",
    "nama_klpd": "Kab. Muko Muko",
    "nama_satker": "Sekretariat DPRD",
    "pagu": 38250000,
    "status_aktif_rup": true,
    "status_delete_rup": false,
    "status_umumkan_rup": "Terumumkan",
    "sumber_dana": "APBD",
    "tahun_anggaran": 2026,
    "tahun_anggaran_dana": 2026,
    "bulan_pengadaan": "Mei",
    "jenis_paket": "Penyedia",
    "metode_pengadaan": "E-Purchasing",
    "volume_pekerjaan": "1 Tahun",
    "spesifikasi_pekerjaan": "Sewa Alat Kantor",
    "jenis_pengadaan": "Jasa"
  },
  {
    "asal_dana": "APBD",
    "asal_dana_klpd": "Kab. Muko Muko",
    "asal_dana_satker": "Dinas Pekerjaan Umum dan Penataan Ruang",
    "jenis_klpd": "KABUPATEN",
    "kd_rup": 63456629,
    "kd_satker": 337178,
    "kd_satker_str": "1.03.2.11.0.00.01.0000",
    "mak": "1.03.10.2.01.0069.5.1.02.01.001.00024.1.1.12.01.03.0001.00312",
    "nama_paket": "Pemeliharaan Rutin Jalan Kabupaten",
    "nama_klpd": "Kab. Muko Muko",
    "nama_satker": "Dinas Pekerjaan Umum dan Penataan Ruang",
    "pagu": 324000,
    "status_aktif_rup": true,
    "status_delete_rup": false,
    "status_umumkan_rup": "Terumumkan",
    "sumber_dana": "APBD",
    "tahun_anggaran": 2026,
    "tahun_anggaran_dana": 2026,
    "bulan_pengadaan": "April",
    "jenis_paket": "Penyedia",
    "metode_pengadaan": "Pengadaan Langsung",
    "volume_pekerjaan": "1 Paket",
    "spesifikasi_pekerjaan": "Perbaikan Ringan",
    "jenis_pengadaan": "Pekerjaan Konstruksi"
  },
  {
    "asal_dana": "APBD",
    "asal_dana_klpd": "Kab. Muko Muko",
    "asal_dana_satker": "Sekretariat Daerah",
    "jenis_klpd": "KABUPATEN",
    "kd_rup": 62843031,
    "kd_satker": 94683,
    "kd_satker_str": "4.01.2.16.2.19.01.0000",
    "mak": "4.01.03.2.01.0001.5.1.02.01.001.00052.8.1.02.01.01.0052.00009",
    "nama_paket": "Belanja Makanan dan Minuman Jamuan",
    "nama_klpd": "Kab. Muko Muko",
    "nama_satker": "Sekretariat Daerah",
    "pagu": 550000,
    "status_aktif_rup": true,
    "status_delete_rup": false,
    "status_umumkan_rup": "Terumumkan",
    "sumber_dana": "APBD",
    "tahun_anggaran": 2026,
    "tahun_anggaran_dana": 2026,
    "bulan_pengadaan": "Februari",
    "jenis_paket": "Penyedia",
    "metode_pengadaan": "E-Purchasing",
    "volume_pekerjaan": "1 Paket",
    "spesifikasi_pekerjaan": "Jamuan Makan Rapat",
    "jenis_pengadaan": "Barang"
  },
  {
    "asal_dana": "APBD",
    "asal_dana_klpd": "Kab. Muko Muko",
    "asal_dana_satker": "Dinas Pekerjaan Umum dan Penataan Ruang",
    "jenis_klpd": "KABUPATEN",
    "kd_rup": 63353389,
    "kd_satker": 337178,
    "kd_satker_str": "1.03.2.11.0.00.01.0000",
    "mak": "2.11.04.2.01.0007.5.1.02.01.001.00008.1.1.12.01.01.0008.00374",
    "nama_paket": "Belanja Suku Cadang Alat Berat",
    "nama_klpd": "Kab. Muko Muko",
    "nama_satker": "Dinas Pekerjaan Umum and Penataan Ruang",
    "pagu": 2800000,
    "status_aktif_rup": true,
    "status_delete_rup": false,
    "status_umumkan_rup": "Terumumkan",
    "sumber_dana": "APBD",
    "tahun_anggaran": 2026,
    "tahun_anggaran_dana": 2026,
    "bulan_pengadaan": "Mei",
    "jenis_paket": "Penyedia",
    "metode_pengadaan": "Pengadaan Langsung",
    "volume_pekerjaan": "1 Unit",
    "spesifikasi_pekerjaan": "Suku Cadang Excavator",
    "jenis_pengadaan": "Barang"
  },
  {
    "asal_dana": "APBD",
    "asal_dana_klpd": "Kab. Muko Muko",
    "asal_dana_satker": "Dinas Tenaga Kerja dan Transmigrasi",
    "jenis_klpd": "KABUPATEN",
    "kd_rup": 63134795,
    "kd_satker": 337180,
    "kd_satker_str": "2.07.3.32.0.00.01.0000",
    "mak": "2.07.01.2.06.0002.5.1.02.01.001.00025.1.1.12.01.03.0002.00080",
    "nama_paket": "Biaya Operasional Lapangan",
    "nama_klpd": "Kab. Muko Muko",
    "nama_satker": "Dinas Tenaga Kerja dan Transmigrasi",
    "pagu": 335000,
    "status_aktif_rup": true,
    "status_delete_rup": false,
    "status_umumkan_rup": "Terumumkan",
    "sumber_dana": "APBD",
    "tahun_anggaran": 2026,
    "tahun_anggaran_dana": 2026,
    "bulan_pengadaan": "Juni",
    "jenis_paket": "Penyedia",
    "metode_pengadaan": "Pengadaan Langsung",
    "volume_pekerjaan": "1 Kali",
    "spesifikasi_pekerjaan": "Transport Lokal",
    "jenis_pengadaan": "Jasa"
  },
  {
    "asal_dana": "APBD",
    "asal_dana_klpd": "Kab. Muko Muko",
    "asal_dana_satker": "Dinas Pekerjaan Umum dan Penataan Ruang",
    "jenis_klpd": "KABUPATEN",
    "kd_rup": 63457344,
    "kd_satker": 337178,
    "kd_satker_str": "1.03.2.11.0.00.01.0000",
    "mak": "1.03.10.2.01.0059.5.2.04.01.001.00003.1.3.04.01.01.0003.00004",
    "nama_paket": "Belanja Modal Irigasi dan Jaringan",
    "nama_klpd": "Kab. Muko Muko",
    "nama_satker": "Dinas Pekerjaan Umum dan Penataan Ruang",
    "pagu": 846080000,
    "status_aktif_rup": true,
    "status_delete_rup": false,
    "status_umumkan_rup": "Terumumkan",
    "sumber_dana": "APBD",
    "tahun_anggaran": 2026,
    "tahun_anggaran_dana": 2026,
    "bulan_pengadaan": "Agustus",
    "jenis_paket": "Penyedia",
    "metode_pengadaan": "Tender",
    "volume_pekerjaan": "1 Paket",
    "spesifikasi_pekerjaan": "Konstruksi Jaringan Irigasi",
    "jenis_pengadaan": "Pekerjaan Konstruksi"
  },
  {
    "asal_dana": "APBD",
    "asal_dana_klpd": "Kab. Muko Muko",
    "asal_dana_satker": "Dinas Tenaga Kerja dan Transmigrasi",
    "jenis_klpd": "KABUPATEN",
    "kd_rup": 63135641,
    "kd_satker": 337180,
    "kd_satker_str": "2.07.3.32.0.00.01.0000",
    "mak": "2.07.01.2.08.0002.5.1.02.02.001.00061.8.1.02.02.01.0061.00006",
    "nama_paket": "Jasa Pengelolaan Kebersihan",
    "nama_klpd": "Kab. Muko Muko",
    "nama_satker": "Dinas Tenaga Kerja dan Transmigrasi",
    "pagu": 21520000,
    "status_aktif_rup": true,
    "status_delete_rup": false,
    "status_umumkan_rup": "Terumumkan",
    "sumber_dana": "APBD",
    "tahun_anggaran": 2026,
    "tahun_anggaran_dana": 2026,
    "bulan_pengadaan": "Januari",
    "jenis_paket": "Penyedia",
    "metode_pengadaan": "E-Purchasing",
    "volume_pekerjaan": "12 Bulan",
    "spesifikasi_pekerjaan": "Cleaning Service",
    "jenis_pengadaan": "Jasa Lainnya"
  },
  {
    "asal_dana": "APBD",
    "asal_dana_klpd": "Kab. Muko Muko",
    "asal_dana_satker": "Dinas Pekerjaan Umum dan Penataan Ruang",
    "jenis_klpd": "KABUPATEN",
    "kd_rup": 63457341,
    "kd_satker": 337178,
    "kd_satker_str": "1.03.2.11.0.00.01.0000",
    "mak": "1.03.10.2.01.0059.5.2.04.01.001.00003.1.3.04.01.01.0003.00004",
    "nama_paket": "Pembangunan Jaringan Distribusi Air Minum",
    "nama_klpd": "Kab. Muko Muko",
    "nama_satker": "Dinas Pekerjaan Umum dan Penataan Ruang",
    "pagu": 1500000000,
    "status_aktif_rup": true,
    "status_delete_rup": false,
    "status_umumkan_rup": "Terumumkan",
    "sumber_dana": "APBD",
    "tahun_anggaran": 2026,
    "tahun_anggaran_dana": 2026,
    "bulan_pengadaan": "September",
    "jenis_paket": "Penyedia",
    "metode_pengadaan": "Tender",
    "volume_pekerjaan": "1 Unit",
    "spesifikasi_pekerjaan": "Pipa HDPE dan Aksesoris",
    "jenis_pengadaan": "Pekerjaan Konstruksi"
  },
  {
    "asal_dana": "APBD",
    "asal_dana_klpd": "Kab. Muko Muko",
    "asal_dana_satker": "Dinas Pekerjaan Umum dan Penataan Ruang",
    "jenis_klpd": "KABUPATEN",
    "kd_rup": 63460070,
    "kd_satker": 337178,
    "kd_satker_str": "1.03.2.11.0.00.01.0000",
    "mak": "1.03.10.2.01.0053.5.2.04.01.001.00003.1.3.04.01.01.0003.00010",
    "nama_paket": "Peningkatan Jalan Lingkungan",
    "nama_klpd": "Kab. Muko Muko",
    "nama_satker": "Dinas Pekerjaan Umum dan Penataan Ruang",
    "pagu": 157826000,
    "status_aktif_rup": true,
    "status_delete_rup": false,
    "status_umumkan_rup": "Terumumkan",
    "sumber_dana": "APBD",
    "tahun_anggaran": 2026,
    "tahun_anggaran_dana": 2026,
    "bulan_pengadaan": "Juli",
    "jenis_paket": "Penyedia",
    "metode_pengadaan": "Tender Cepat",
    "volume_pekerjaan": "1 Paket",
    "spesifikasi_pekerjaan": "Aspal Hotmix",
    "jenis_pengadaan": "Pekerjaan Konstruksi"
  },
  {
    "asal_dana": "APBD",
    "asal_dana_klpd": "Kab. Muko Muko",
    "asal_dana_satker": "Dinas Tenaga Kerja dan Transmigrasi",
    "jenis_klpd": "KABUPATEN",
    "kd_rup": 63097245,
    "kd_satker": 337180,
    "kd_satker_str": "2.07.3.32.0.00.01.0000",
    "mak": "2.07.01.2.08.0004.5.1.02.02.001.00030.8.1.02.02.01.0030.00012",
    "nama_paket": "Belanja Pemeliharaan Kendaraan Dinas",
    "nama_klpd": "Kab. Muko Muko",
    "nama_satker": "Dinas Tenaga Kerja dan Transmigrasi",
    "pagu": 29946192,
    "status_aktif_rup": true,
    "status_delete_rup": false,
    "status_umumkan_rup": "Terumumkan",
    "sumber_dana": "APBD",
    "tahun_anggaran": 2026,
    "tahun_anggaran_dana": 2026,
    "bulan_pengadaan": "Februari",
    "jenis_paket": "Penyedia",
    "metode_pengadaan": "Pengadaan Langsung",
    "volume_pekerjaan": "1 Paket",
    "spesifikasi_pekerjaan": "Service Rutin dan Ganti Oli",
    "jenis_pengadaan": "Jasa"
  }
];
